import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { IBM_Plex_Mono } from "next/font/google";

import { cn } from "@/lib/utils";
import type { Metadata } from "next";

const fontHeading = IBM_Plex_Mono({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-heading",
	weight: "700",
});

const fontBody = IBM_Plex_Mono({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-body",
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background  antialiased",
					fontHeading.variable,
					fontBody.variable,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
